config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get 'block_user/:id', to: 'users#block_user', as: :block_user
    get 'unblock_user/:id', to: 'users#unblock_user', as: :unblock_user
    get 'add_admin/:id', to: 'users#add_admin', as: :add_admin
    get 'remove_admin/:id', to: 'users#remove_admin', as: :remove_admin
    get 'delete_user/:id', to: 'users#delete_user', as: :delete_user
    get 'user_management', to: 'users#user_management', as: :user_management
  end
  get 'blocked', to: 'pages#blocked'
  resources :collections do
    resources :items
  end
  resources :items, only: [:new, :create]
  resources :items, only: [:index, :show]
  resources :tags, only: [:show]

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  CATEGORIES = ['Books', 'Signs', 'Silverware', 'Other'].freeze

  validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

    before_action :set_collection, only: [:show, :edit, :update, :destroy]

    def index
      @collections = current_user.collections
    end
    def show
        @collection = Collection.find(params[:id])
        @items = @collection.items
    end
    def new
      @collection = current_user.collections.build
      @categories = Collection::CATEGORIES
    end
    def edit
      @categories = Collection::CATEGORIES
    end
    def create
      @collection = current_user.collections.build(collection_params)
      @categories = Collection::CATEGORIES
      if @collection.save
        redirect_to @collection, notice: 'Collection was successfully created.'
      else
        render :new
      end
    end
    def update
      @categories = Collection::CATEGORIES
      if @collection.update(collection_params)
        redirect_to @collection, notice: 'Collection was successfully updated.'
      else
        render :edit
      end
    end
    def destroy
      @collection.destroy
      redirect_to collections_url, notice: 'Collection was successfully destroyed.'
    end
  
    private
    def set_collection
      @collection = Collection.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "Collection not found."
    end
    def collection_params
      params.require(:collection).permit(:name, :description, :category)
    end
end
  

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_with(model: @collection, local: true) do |form| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>
      <ul>
        <% @collection.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(@categories, collection.category) %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Edit Collection</h1>
<%= render 'form', collection: @collection, categories: @categories %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <h1>My Collections</h1>
      <ul>
        <% @collections.each do |collection| %>
          <li><%= link_to collection.name, collection %></li>
        <% end %>
      </ul>
      <%= link_to 'New Collection', new_collection_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/collections/new.html.erb
<h1>New Collection</h1>
<%= render 'form', collection: @collection, categories: @categories %>
<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
        <h1><%= @collection.name %></h1>
        <p><strong><%=t(:description)%>:</strong> <%= @collection.description %></p>
        <p><strong><%=t(:category)%>:</strong> <%= @collection.category %></p>
        <% if @items.any? %>
          <ul>
            <% @items.each do |item| %>
              <li><%= item.name %></li>
            <% end %>
          </ul>
        <% else %>
          <p>No items in this collection.</p>
        <% end %>
        <% if user_signed_in? && current_user == @collection.user %>
        <div class="btn-group mb-2" role="group" aria-label="Collection Actions">
          <%= link_to 'Edit', edit_collection_path(@collection), class: 'btn btn-primary' %>
          <%= button_to 'Delete', collection_path(@collection), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <% end %>
        <div class="btn-group mb-2" role="group" aria-label="Back Button">
          <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
        </div>
      </div>
  </div>
</div>