config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get 'block_user/:id', to: 'users#block_user', as: :block_user
    get 'unblock_user/:id', to: 'users#unblock_user', as: :unblock_user
    get 'add_admin/:id', to: 'users#add_admin', as: :add_admin
    get 'remove_admin/:id', to: 'users#remove_admin', as: :remove_admin
    get 'delete_user/:id', to: 'users#delete_user', as: :delete_user
    get 'user_management', to: 'users#user_management', as: :user_management
  end
  get 'blocked', to: 'pages#blocked'
  resources :collections do
    resources :items
  end
  resources :items, only: [:new, :create]
  resources :items, only: [:index, :show]
  resources :tags, only: [:show]

  get "up" => "rails/health#show", as: :rails_health_check

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <% if user_signed_in? %>
        <p><%=t(:hello)%>, <%= current_user.email %>!</p>
        <%= link_to 'My Collections', collections_path, class: 'btn btn-primary mb-2' %>
        <%= link_to 'Create Collection', new_collection_path, class: 'btn btn-primary mb-2' %>
        <% if current_user.collections.any? && current_user.collections.any? { |collection| collection.items.any? } %>
          <%= link_to 'My Items', items_path, class: 'btn btn-primary mb-2' %>
        <% end %>
        <% @collection = current_user.collections.first %>
        <% if @collection.present? %>
          <%= link_to 'Create Item', new_item_path(collection_id: @collection.id), class: 'btn btn-primary mb-2' %>
        <% else %>
          <p class="mb-2">You must create a collection first before adding items.</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>