config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root 'home#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    get 'block_user/:id', to: 'users#block_user', as: :block_user
    get 'unblock_user/:id', to: 'users#unblock_user', as: :unblock_user
    get 'add_admin/:id', to: 'users#add_admin', as: :add_admin
    get 'remove_admin/:id', to: 'users#remove_admin', as: :remove_admin
    get 'delete_user/:id', to: 'users#delete_user', as: :delete_user
    get 'user_management', to: 'users#user_management', as: :user_management
  end
  get 'blocked', to: 'pages#blocked'
  resources :collections do
    resources :items
  end
  resources :items, only: [:new, :create]
  resources :items, only: [:index, :show]
  resources :tags, only: [:show]

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :collection
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_collection, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    if params[:collection_id]
      @items = current_user.collections.find(params[:collection_id]).items
    else
      @items = Item.joins(:collection).where(collections: { user_id: current_user.id })
    end
  end
  def show
  end
  def new
    @item = Item.new
  end
  def edit
  end
  def create
    @collection = current_user.collections.find(item_params[:collection_id])
    @item = @collection.items.build(item_params)
    if @item.save
      redirect_to collection_item_path(@collection, @item), notice: 'Item was successfully created.'
    else
      render :new
    end
  end
  def update
    @collection = current_user.collections.find(item_params[:collection_id])

    if @item.update(item_params)
      redirect_to collection_item_path(@collection, @item), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    @item.destroy
    redirect_to collection_items_path(@collection), notice: 'Item was successfully destroyed.'
  end

  private
    def set_collection
      @collection = Collection.find(params[:collection_id])
    rescue ActiveRecord::RecordNotFound
      @collection = nil
    end
    def set_item
      @item = @collection.items.find(params[:id])
    end
    
    def item_params
      params.require(:item).permit(:name, :tags, :collection_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [@collection, @item], local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>
  <div class="field">
    <%= form.label :collection_id %>
    <%= form.collection_select :collection_id, current_user.collections, :id, :name, prompt: true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render 'form' %>
<%= link_to 'Show', [@collection, @item] %> |
<%= link_to 'Back', collection_items_path(@collection) %>

app/views/items/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <h1>Items</h1>
      <ul>
        <% @items.each do |item| %>
          <li>
            <%= link_to item.name, collection_item_path(item.collection, item) %>
          </li>
        <% end %>
      </ul>
      <%= link_to 'New Item', new_item_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>
<%= link_to 'Back', items_path(@collection) %>

app/views/items/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6 text-center">
      <p><strong><%=t(:name)%>:</strong> <%= @item.name %></p>
      <p><strong><%=t(:tags)%>:</strong> <%= @item.tags %></p>
      <% if user_signed_in? && current_user == @item.collection.user %>
      <div class="btn-group mb-2" role="group" aria-label="Collection Actions">
        <%= link_to 'Edit', edit_collection_item_path(@collection, @item), class: 'btn btn-primary' %> |
        <%= button_to 'Delete', collection_item_path(@collection, @item), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %> |
      </div>
      <% end %>
      <div class="btn-group mb-2" role="group" aria-label="Back Button">
        <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>